export const DELETE_CUSTOMERS = "DELETE_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const EDIT_CUSTOMERS = "EDIT_CUSTOMERS";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const UPLOAD_FILE_CUSTOMER = "UPLOAD_FILE_CUSTOMER";
